version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: my-mongo
    restart: always
    ports:
      - "27017:27017"  # Host:Container
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: my-mosquitto
    restart: always
    ports:
      - "1883:1883"  # MQTT default port
      - "9001:9001"  # WebSocket port for MQTT over WebSocket
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_logs:/mosquitto/log
      - ./config/mosquitto/config:/mosquitto/config
    environment:
      - MOSQUITTO_CONFIG_FILE=/mosquitto/config/mosquitto.conf

volumes:
  mongo_data:
  mosquitto_data:
  mosquitto_logs:
