version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: my-mongo
    restart: always
    ports:
      - "27017:27017"  # Host:Container
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: